<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container75nui4l\testsKnpU_LoremIpsumBundle_Tests_KnpULoremIpsumTestingKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container75nui4l/testsKnpU_LoremIpsumBundle_Tests_KnpULoremIpsumTestingKernelTestDebugContainer.php') {
    touch(__DIR__.'/Container75nui4l.legacy');

    return;
}

if (!\class_exists(testsKnpU_LoremIpsumBundle_Tests_KnpULoremIpsumTestingKernelTestDebugContainer::class, false)) {
    \class_alias(\Container75nui4l\testsKnpU_LoremIpsumBundle_Tests_KnpULoremIpsumTestingKernelTestDebugContainer::class, testsKnpU_LoremIpsumBundle_Tests_KnpULoremIpsumTestingKernelTestDebugContainer::class, false);
}

return new \Container75nui4l\testsKnpU_LoremIpsumBundle_Tests_KnpULoremIpsumTestingKernelTestDebugContainer([
    'container.build_hash' => '75nui4l',
    'container.build_id' => '457dfeca',
    'container.build_time' => 1579787240,
], __DIR__.\DIRECTORY_SEPARATOR.'Container75nui4l');
